// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDLEf_prpWTpakrkB-PgtOzRgIkCiC2lCg',
    appId: '1:1005920885227:web:d6f0a643a9b6f12b09e1ae',
    messagingSenderId: '1005920885227',
    projectId: 'proxima-flutter',
    authDomain: 'proxima-flutter.firebaseapp.com',
    storageBucket: 'proxima-flutter.appspot.com',
    measurementId: 'G-Y2ZQKHPDXW',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAhegYhWQjjBNHA2jhd-DM_BHPSfWSvgdQ',
    appId: '1:1005920885227:android:210269ba109639a809e1ae',
    messagingSenderId: '1005920885227',
    projectId: 'proxima-flutter',
    storageBucket: 'proxima-flutter.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCfUGe_8cBVkLdnDI09Xvbx52T914B88ik',
    appId: '1:1005920885227:ios:6a1dab6b632fc9b709e1ae',
    messagingSenderId: '1005920885227',
    projectId: 'proxima-flutter',
    storageBucket: 'proxima-flutter.appspot.com',
    iosClientId: '1005920885227-ioec9ucqm3vnoeqa01tnfremtdmhob4p.apps.googleusercontent.com',
    iosBundleId: 'com.example.flutterApplication1',
  );
}
